// const resList=[
// {name:"Shivam",
// rating:"4.8",
// cuisine:"Indian",
// time:"30min"},
// {name:"Ashirwad",
// rating:"4.6",
// cuisine:"Indian",
// time:"30min"},
// {name:"swad",
// rating:"3.8",
// cuisine:"Indian",
// time:"30min"},
// {name:"Sudama",
// rating:"3.9",
// cuisine:"Indian",
// time:"30min"},
// {name:"Atithi",
// rating:"4.0",
// cuisine:"Indian",
// time:"30min"},
// {name:"KKFC",
// rating:"3.5",
// cuisine:"Indian",
// time:"30min"},
// {name:"BHOLA ",
// rating:"4.2",
// cuisine:"Indian",
// time:"30min"},
// {name:"Ajmani cafe",
// rating:"3.9",
// cuisine:"Indian",
// time:"30min"},
// {name:"Mughal Dhaba",
// rating:"4.3",
// cuisine:"Indian",
// time:"30min"},
// {name:"Awadh restaurant",
// rating:"3.8",
// cuisine:"Indian",
// time:"30min"},


// ]